### ISSUE TITLE
Template "displayNonStandard" not called in template "tableValueListsInTable"

### ISSUE THREAD

**Issue by dostiep** [lexjansen/define-xml-2.1-stylesheets#10]
I don't know if it was intentionnal or not but I find it odd that template "displayNonStandard" is not called in template "tableValueListsInTable" even though the "def:IsNonStandard" attribute exists for element "../def:ValueListDef/ItemRef".

Moreover, it seems like the child element "Description" from element "def:ValueListDef" is nowhere to be found in the stylesheet to be displayed in web browser.

I personnaly don't see any value in having a "Description" child element for "def:ValueListDef" but I would expect that information displayed if available.

**Comment by dostiep** [comment]
I can't find either the child element "Description" from element "CodeList".

**Comment by lexjansen** [comment]
It was intentional. def:IsNonStandard is not applicable for VLM. See specification 5.3.9.2: 

"Permitted for any ItemRef that represents a non-standard variable in an SDTM or SEND dataset when the ODM Context attribute value is "Other"
Is not used with an ItemRef that represents a value level metadata for an SDTMIG SUPPQUAL dataset
Has no meaning for ADaM, so shall not be used for ADaM variables"

I agree about the ValueList Description, but would need to find a good location for the display.

**Comment by dostiep** [comment]
Thank you Lex, I guess I overlooked that one. 

I can't think of any good location either for ValueList Description. 

The only place left is column "Where Condition" but not sure it would belong there.

![image](https://user-images.githubusercontent.com/111854855/224397840-0a307cb6-0da8-4f09-9972-b29cb5292257.png)

**Comment by lexjansen** [comment]
I think I found a solution for display. When you hover over the VLM link:
![image](https://user-images.githubusercontent.com/11705643/224399863-999b6083-5e70-4750-9efb-e216f5cd3c5d.png)

**Comment by dostiep** [comment]
Looks pretty good to me!

**Comment by lexjansen** [comment]
Added display of ValueList Description
